[package]
name = "web"
version = "0.1.0"
authors = ["yorhel"]

[lib]
name = "web"
crate-type = ["lib", "staticlib"]

[dependencies]
regex = "0.2.10"
lazy_static = "1.0.0"

# Add debugging symbols even in release mode, in order to help with profiling.
[profile.release]
debug = true
